package de.hasait.eclipse.ccg.javag.application.model;

import org.eclipse.core.runtime.IProgressMonitor;

import de.hasait.eclipse.common.ContentBuffer;

/**
 * Generated by CommentCodeGen: /ccgtest/ccg/test1.ccg.xml
 */
public class SingleProperty extends AbstractProperty {
	private final String _getMethodName;

	private final String _setMethodName;

	/**
	 * Constructor.
	 */
	public SingleProperty(Bean bean, String name, String description, String type, String backref,
	      String getterVisibility, String setterVisibility) {
		super(bean, name, description, type, backref, getterVisibility, setterVisibility);

		if (type.equals("boolean")) {
			_getMethodName = "is" + getCapName();
		} else {
			_getMethodName = "get" + getCapName();
		}
		_setMethodName = "set" + getCapName();
	}

	/**
	 * @return the getMethodName
	 */
	public final String getGetMethodName() {
		return _getMethodName;
	}

	/**
	 * @return the setMethodName
	 */
	public final String getSetMethodName() {
		return _setMethodName;
	}

	public String getAdderCall(String instance, String value) {
		return instance + "." + getSetMethodName() + "(" + value + ")";
	}

	public String getRemoverCall(String instance, String value) {
		return instance + "." + getSetMethodName() + "(null)";
	}

	public void write(ContentBuffer content, IProgressMonitor monitor) {
		super.write(content, monitor);

		//
		// variable
		//
		content.p("private " + getType() + " " + getVarName() + ";");

		content.p();

		//
		// getter
		//
		content.pi("/**", " * ");
		content.p("Return the value of property " + getName() + ".");
		if (getDescription() != null) {
			content.p();
			content.p(getDescription());
		}
		content.p();
		content.p("@return The value of property " + getName() + ".");
		content.pu(" */");

		content.pi(getGetterVisibility() + " final " + getType() + " " + getGetMethodName() + "() {");
		content.p("return " + getVarName() + ";");
		content.pu("}");

		content.p();

		//
		// setter
		//
		content.pi("/**", " * ");
		content.p("Set the value of property " + getName() + " to the specified value.");
		if (getBackrefProperty() != null) {
			content.p("Referred from " + getBackrefProperty().getJavaDocFullName()
			      + ", which will be updated by this method.");
		}
		if (getDescription() != null) {
			content.p();
			content.p(getDescription());
		}
		content.p();
		content.p("@param " + getName() + " The new value for property " + getName() + ".");
		content.pu(" */");

		content.pi(getSetterVisibility() + " final void " + getSetMethodName() + "(final " + getType() + " " + getName()
		      + ") {");
		if (getBackrefProperty() == null) {
			content.p(getVarName() + " = " + getName() + ";");
		} else {
			content.pi("if (" + getVarName() + " == " + getName() + ") {");
			content.p("return;");
			content.pu("}");
			String oldName = "old" + getCapName();
			content.p(getType() + " " + oldName + " = " + getVarName() + ";");
			content.pi("if (" + getVarName() + " != null) {");
			content.p("" + getVarName() + " = null;");
			content.p(getBackrefProperty().getRemoverCall(oldName, "this") + ";");
			content.pu("}");
			content.p(getVarName() + " = " + getName() + ";");
			content.pi("if (" + getName() + " != null) {");
			content.p(getBackrefProperty().getAdderCall(getName(), "this") + ";");
			content.pu("}");
		}
		content.pu("}");

		content.p();
	}
}
