/*
 * $Id: SingleProperty.java,v 1.5 2007-01-06 00:39:04 concentus Exp $
 * 
 * Copyright 2006 Sebastian Hasait
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.hasait.eclipse.ccg.javag.application.model;

import de.hasait.eclipse.ccg.javag.lowlevel.MSingleProperty;
import de.hasait.eclipse.common.xml.XElement;

/**
 * Generated by CommentCodeGen: /ccgtest/ccg/test1.ccg.xml
 */
public class SingleProperty extends AbstractProperty {
	/**
	 * Constructor.
	 */
	public SingleProperty(final Bean pBean, final XElement pConfigElement) {
		super(pBean, new MSingleProperty(), pConfigElement);
	}

	public final MSingleProperty getSingleProperty() {
		return (MSingleProperty) getProperty();
	}
}
