<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jsm"
    nsURI="">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMElement" abstract="true">
    <eOperations name="getFullQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMPackageContainer" abstract="true"
      eSuperTypes="#//AbstractMElement">
    <eOperations name="getFolder" eType="#//XFolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//MPackage" containment="true" eOpposite="#//MPackage/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MRoot" eSuperTypes="#//AbstractMPackageContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folder" lowerBound="1"
        eType="#//XFolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalTypes" upperBound="-1"
        eType="#//AbstractMExternalType" containment="true" eOpposite="#//AbstractMExternalType/root"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPackage" eSuperTypes="#//AbstractMPackageContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AbstractMPackageContainer" eOpposite="#//AbstractMPackageContainer/children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnits" upperBound="-1"
        eType="#//MCompilationUnit" containment="true" eOpposite="#//MCompilationUnit/package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMTypeContainer" abstract="true"
      eSuperTypes="#//AbstractMElement">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//AbstractMDeclaredType" containment="true" eOpposite="#//AbstractMDeclaredType/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MCompilationUnit" eSuperTypes="#//AbstractMTypeContainer">
    <eOperations name="getFile" eType="#//XFile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="#//MPackage" eOpposite="#//MPackage/compilationUnits"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//IType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMDeclaredType" abstract="true"
      eSuperTypes="#//AbstractMTypeContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//AbstractMTypeContainer" eOpposite="#//AbstractMTypeContainer/types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMExternalType" abstract="true"
      eSuperTypes="#//AbstractMElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//MRoot"
        eOpposite="#//MRoot/externalTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IType" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMClass" abstract="true" interface="true"
      eSuperTypes="#//IType"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDeclaredClass" eSuperTypes="#//IMClass #//AbstractMDeclaredType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//IMClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="#//IMInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticFields" upperBound="-1"
        eType="#//MStaticClassFieldDeclaration" containment="true" eOpposite="#//MStaticClassFieldDeclaration/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceFields" upperBound="-1"
        eType="#//MInstanceClassFieldDeclaration" containment="true" eOpposite="#//MInstanceClassFieldDeclaration/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MExternalClass" eSuperTypes="#//IMClass #//AbstractMExternalType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMInterface" abstract="true" interface="true"
      eSuperTypes="#//IType"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDeclaredInterface" eSuperTypes="#//IMInterface #//AbstractMDeclaredType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//IMInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//MConstantInterfaceFieldDeclaration" containment="true" eOpposite="#//MConstantInterfaceFieldDeclaration/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MExternalInterface" eSuperTypes="#//IMInterface #//AbstractMExternalType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMFieldDeclaration" abstract="true"
      eSuperTypes="#//AbstractMElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//IType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="#//AbstractCExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMClassFieldDeclaration" abstract="true"
      eSuperTypes="#//AbstractMFieldDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//MVisibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStaticClassFieldDeclaration" eSuperTypes="#//AbstractMClassFieldDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//MDeclaredClass"
        eOpposite="#//MDeclaredClass/staticFields"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInstanceClassFieldDeclaration" eSuperTypes="#//AbstractMClassFieldDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//MDeclaredClass"
        eOpposite="#//MDeclaredClass/instanceFields"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConstantInterfaceFieldDeclaration"
      eSuperTypes="#//AbstractMFieldDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//MDeclaredInterface"
        eOpposite="#//MDeclaredInterface/constants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodImplementation"/>
  <eClassifiers xsi:type="ecore:EClass" name="MConstructorImplementation"/>
  <eClassifiers xsi:type="ecore:EClass" name="CCodeBuffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//AbstractCStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCStatement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CUnparsedStatement" eSuperTypes="#//AbstractCStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CUnparsedExpression" eSuperTypes="#//AbstractCExpression"/>
  <eClassifiers xsi:type="ecore:EDataType" name="XFolder" instanceClassName="de.hasait.eclipse.common.resource.XFolder"/>
  <eClassifiers xsi:type="ecore:EDataType" name="XFile" instanceClassName="de.hasait.eclipse.common.resource.XFile"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MVisibility">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="PRIVATE" value="1"/>
    <eLiterals name="PROTECTED" value="2"/>
    <eLiterals name="PUBLIC" value="3"/>
  </eClassifiers>
</ecore:EPackage>
